In [14]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.preprocessing import label_binarize

# Load the digits dataset
data_set = load_digits()

X = data_set.data
Y = data_set.target

# Split the data 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=72)

# Initializing 
model_rf = RandomForestClassifier(n_estimators=100, random_state=72)
model_rf.fit(X_train, Y_train)


pred_rf = model_rf.predict(X_test)

accuracy = accuracy_score(Y_test, pred_rf)
print(f"Accuracy: {accuracy:.2f}")

print("\nClassification Report:")
print(classification_report(Y_test, pred_rf))


print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, pred_rf))


Y_test_bin = label_binarize(Y_test, classes=np.unique(Y))
Y_score = model_rf.predict_proba(X_test)


for i in range(Y_test_bin.shape[1]):
    roc_auc = roc_auc_score(Y_test_bin[:, i], Y_score[:, i])
    print(f"Class {i} AUC-ROC Score: {roc_auc:.2f}")
    

bal_acc_rf = 100 * (accuracy_score(Y_test, pred_rf))
print(f"\nRandom Forest Balanced Accuracy: {bal_acc_rf:.2f}%")

roc_rf = roc_auc_score(Y_test_bin, Y_score, average='macro')
print(f"Random Forest ROC AUC Score: {roc_rf:.2f}")


Accuracy: 0.98

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.97      1.00      0.98        32
           2       0.98      1.00      0.99        41
           3       0.97      1.00      0.98        30
           4       1.00      0.97      0.98        32
           5       1.00      0.94      0.97        36
           6       0.97      1.00      0.99        39
           7       0.97      1.00      0.98        31
           8       1.00      0.92      0.96        38
           9       0.98      1.00      0.99        41

    accuracy                           0.98       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.98      0.98      0.98       360


Confusion Matrix:
[[40  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 30  0  0  0  0  0  0]
 [ 0  0  0  0 31  0  0  1  0  0]
 [ 0  0  0  0  0 3